version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sale
      POSTGRES_USER: love
      POSTGRES_DB: love-sale
    ports:
      - 5433:5433
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
